server:
  port: ${PORT:0}
  servlet:
    context-path: /api/courier

spring:
  application:
    name: courier-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}